### ISSUE TITLE
Chrome Cast cannot find chrome cast devices

### ISSUE THREAD

**Issue by adamszeptycki** [jwplayer/jwplayer-ios-bestPracticeApps#18]
I have built JWCasting from this repo add a key and everything (video player works). BUT
it doesn't find any devices. There is a chrome cast device right next to my phone and other apps (YouTube and TedTalks app) don't have any problem finding it.
Any clues how can I debug it?

**Comment by karimMourra** [comment]
Hi @adamszeptycki , are you using a specific chrome cast receiver app id ? Have you made any modifications to the JWCasting app ? Are you using the latest SDK ? The latest SDK uses Google Chrome SDK version 4.3.5, so you will have to run `pod update` to ensure you have the latest dependencies.

Lastly, Youtube and Netflix should not be used for comparison. Per Google's [Cast Discovery documentation](https://developers.google.com/cast/docs/discovery):
> Do not use the Netflix or YouTube apps to test discovery, as these use some specialized discovery mechanisms.

>

**Comment by karimMourra** [comment]
To ensure the issue is not related to your network, i recommend comparing against Google's basic sample cast app https://github.com/googlecast/CastHelloVideo-ios

**Comment by adamszeptycki** [comment]
1. The only change I did was provide my JWPlayer license Key in plist file.
2. I did pod install after pulling your code yesterday so I assume I have the latest code and deps.
3. So TedTalk and one of your competitor's example app worked flawlessly, (so we don't compare to YouTube)

**Comment by adamszeptycki** [comment]
>  are you using a specific chrome cast receiver app id ?

No.

Any other ideas what can I do make it work?

**Comment by karimMourra** [comment]
Hi @adamszeptycki I believe it is possible you are not using the latest version of the Google Cast SDK. Our current best practice app contains an out of date line `self.castController.chromeCastReceiverAppID = kGCKMediaDefaultReceiverApplicationID;`. The `kGCKMediaDefaultReceiverApplicationID` constant was replaced by `kGCKDefaultMediaReceiverApplicationID` in Google Cast 4.x, therefore if your application is compiling, it must be using an older version. I am pushing the update to master. Please pull from master, pod install and pod update and let me know if the issue persists.

**Comment by karimMourra** [comment]
The google cast SDK logs its version, you should see `GoogleCast framework version 4.3.5.13` in the logs

**Comment by adamszeptycki** [comment]
Yep that was it
