### ISSUE TITLE
Remote thumb url is not working for video

### ISSUE THREAD

**Issue by aadeshmindtickle** [jwplayer/jwplayer-ios-bestPracticeApps#46]
### Expected Behavior

jwconfig.image = "<Remote url>"
should work

### Actual Behavior

Image is not displayed on the video

### Steps to reproduce

set config.image to remote url and it doesn't work

### Environment

- *iOS | v13.1*
- *3.14.0*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by karimMourra** [comment]
Hi @aadeshmindtickle , do you have a sample url ? Our test urls are working.

**Comment by aadeshmindtickle** [comment]
@karimMourra 
https://cf-ap1.mindtickle.com/1093787813831792498/1579496201862/1093787813831792498/1572603149592/1093787813831792498/1571736012130/1093787813831792498/1568886519847/1093787813831792498/1568885040713/1093787813831792498/1154689112662666565/1564134739_VOS1Video.mp4/thumb/mp4-00001.png?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2YtYXAxLm1pbmR0aWNrbGUuY29tLzEwOTM3ODc4MTM4MzE3OTI0OTgvMTU3OTQ5NjIwMTg2Mi8xMDkzNzg3ODEzODMxNzkyNDk4LzE1NzI2MDMxNDk1OTIvMTA5Mzc4NzgxMzgzMTc5MjQ5OC8xNTcxNzM2MDEyMTMwLzEwOTM3ODc4MTM4MzE3OTI0OTgvMTU2ODg4NjUxOTg0Ny8xMDkzNzg3ODEzODMxNzkyNDk4LzE1Njg4ODUwNDA3MTMvMTA5Mzc4NzgxMzgzMTc5MjQ5OC8xMTU0Njg5MTEyNjYyNjY2NTY1LzE1NjQxMzQ3MzlfVk9TMVZpZGVvLm1wNC90aHVtYi9tcDQtMDAwMDEucG5nIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTkyNTc0NjQxfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=GJDwa8Fb5kVi4s9Ie4JIXySHMx-~DEHd4Ud1Ntms3VPtBKg~Tygt7kL1aPmXlMklU24YCrFbGmVO5btqB9jjvpN~sLfjoUdgXT7W0J22n~Dv4anvEP4fTJMS31hp9W7GXX1uxbvfziVKOvQw8L--eluS1DpKRE3-lvgeUQ9TD6A_&Key-Pair-Id=APKAJRHSQBGT5CW7P2CA

**Comment by karimMourra** [comment]
@aadeshmindtickle It worked in our test app.
<img width="420" alt="Screen Shot 2020-05-20 at 6 30 00 PM" src="https://user-images.githubusercontent.com/12138319/82503892-200bc380-9ac8-11ea-9872-fcfba16b6b01.png">
I noticed it took  a while for it to appear.  Could you  try again and  wait  a few seconds ?
If that doesn't work ,  I will need you to report a bug via our [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner

**Comment by aadeshmindtickle** [comment]
No luck for me still. Interestingly it appears when I turn off the network. The thumb image appears with message "No internet connection available". I tried support portal for other issues but no reply :(

**Comment by karimMourra** [comment]
@AmitaiB please follow up when you have the chance
