### ISSUE TITLE
Subtitles not working on v3.14.0 which is working on 3.3.0

### ISSUE THREAD

**Issue by aadeshmindtickle** [jwplayer/jwplayer-ios-bestPracticeApps#47]
### Expected Behavior

Subtitles which are working in demo app v3.3.0 should work on v3.14.0

### Actual Behavior

Subtitles stopped working after pod update
### Steps to reproduce

1. Take demo app add subtitles; make sure its working fine
2. just update the pod version 
3. subtitles stopped working

### Environment

- *iPhone*
- *iOS | 13.4.1*
- *3.14.0*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by karimMourra** [comment]
Hi @aadeshmindtickle subtitles are working fine with our test assets. Do you have a test stream and configuration so we can try to reproduce your issue ? By steps to reproduce we mean  steps to reproduce the bug (i.e. setup player, press play, toggle caption menu).

**Comment by aadeshmindtickle** [comment]
@karimMourra I have provided the details on the support ticket and they have acknowledged the issue and escalated to mobile team.
