### ISSUE TITLE
"No internet connection" is shown even for locally played file

### ISSUE THREAD

**Issue by aadeshmindtickle** [jwplayer/jwplayer-ios-bestPracticeApps#49]
### Expected Behavior

*Video or audio file should be playable or continue to play*

### Actual Behavior

*We get screen with message "No Internet Connection" and Video Thumbnail image*

### Steps to reproduce

1. Connect your device to internet (Wifi or Mobile network).
2. Play a locally stored file.
3. While the video/ audio is being played; turn off the internet.  Video/ Audio stops playing.
4. Please see turn off the internet only when video is playing to reproduce the issue. If the network is turned OFF before playing the video then video works fine

### Environment

- *iphone | 11*
- *iOS | v13.4.1*
- *3.14*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by aadeshmindtickle** [comment]
@karimMourra  can we disabled the internet check for local files ?

**Comment by AmitaiB** [comment]
Hello @aadeshmindtickle ,
As it happens, this behavior is a known issue, and the fix is to be included in the JWP iOS SDK v3.15.1 release.
