### ISSUE TITLE
Live videos don't work in version 4.0

### ISSUE THREAD

**Issue by rodrigomatosc** [jwplayer/jwplayer-ios-bestPracticeApps#62]
ERROR: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle:  with name '/XIBS/LiveMediaInterface

**Comment by rodrigomatosc** [comment]
### Expected Behavior

*Describe expected behavior*

### Actual Behavior

Videos stopped working after put a live url

### Steps to reproduce

1. Download a Demo 
2. Replace the video link with a live video link

### Environment

- IPhone
- IOS 14.5
- 4.0.0

**Comment by ShubhamTickledMedia** [comment]
Hi @rodrigomatosc
did you fix this issue?

I am also facing the same issue :(
