### ISSUE TITLE
Live videos don't work in version 4.0

### ISSUE THREAD

**Issue by ShubhamTickledMedia** [jwplayer/jwplayer-ios-bestPracticeApps#65]
### Expected Behavior
Live streaming URLs should work perfectly.

### Actual Behavior

Live streaming URLs are crashing as:
`BasicPlayer-Swift.app/Frameworks/JWPlayerKit.framework> (loaded)' with name '/XIBS/LiveMediaInterface''
terminating with uncaught exception of type NSException`

### Steps to reproduce

1. Download the sample app, register key
2. Run the Basic Swift Sample App
3. It will show crash at first glance
4. Used URL: `https://playertest.longtailvideo.com/adaptive/oceans/oceans.m3u8`

### Environment

- iPhone SE 2
- 14.0
- 4.0.0

----------------------------------------------------------------------------------------

**Comment by rodrigomatosc** [comment]
Hi @ShubhamTickledMedia, I think this problem is only in emulators. Try run this in a fisical device please.
