### ISSUE TITLE
Implementing playbackStateDelegate leads to empty screen

### ISSUE THREAD

**Issue by ShubhamTickledMedia** [jwplayer/jwplayer-ios-bestPracticeApps#71]
### Expected Behavior

After setting `playbackStateDelegate` when the playlist gets loaded, we are experiencing an empty screen with the play button.

### Actual Behavior

It should play the video as expected.

### Steps to reproduce

1. Implement player view
2. Set playbackStateDelegate delegate
3. Implement all the required delegate function.
4. Try to play the video once `didLoadPlaylist` is called.

### Environment

- iPhone 7
- iOS 14, iOS 15
- 4.0.0

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ShubhamTickledMedia** [comment]
![Simulator Screen Shot - iPhone SE - 14 - 2021-09-22 at 11 44 38](https://user-images.githubusercontent.com/89381218/134292524-97643cd9-3b45-42f4-971b-227b6a041b0a.png)

**Comment by ShubhamTickledMedia** [comment]
In view hierarchy when the delegate is not set then `VoDMediaView` is present.
![Screenshot 2021-09-22 at 12 40 52 PM](https://user-images.githubusercontent.com/89381218/134299151-b5391f6e-190c-4cd1-9b70-068292ea9a93.png

In view hierarchy when the delegate is set then only `BackdropView` is present. It's playing audio well, but no video view along with the default controls :( 
![Screenshot 2021-09-22 at 12 43 40 PM](https://user-images.githubusercontent.com/89381218/134299155-6475e0c4-922d-4cdb-ace4-6d4dba8e55ec.png)
)

**Comment by mukyasa** [comment]
@AmitaiB Kindly help  us to solve this issue, Thanks
