### ISSUE TITLE
Error Archiving app

### ISSUE THREAD

**Issue by jmltoro** [jwplayer/jwplayer-ios-bestPracticeApps#81]
My application works fine in iOS device and iOS Simulator but when I try to distribute app ah-hoc to any device, after compiling bitcode, I get this error:

_ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -L /var/folders/9r/ggfdl08s5ds_k271dkw3ff9h0000gn/T/ipatool20220117-39826-jo4ts7/thinned-out/arm64/Payload/CanalSurTV.app/Frameworks --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -o /var/folders/9r/ggfdl08s5ds_k271dkw3ff9h0000gn/T/ipatool20220117-39826-jo4ts7/thinned-out/arm64/Payload/CanalSurTV.app/Frameworks/JWPlayerKit.framework/JWPlayerKit --generate-dsym /var/folders/9r/ggfdl08s5ds_k271dkw3ff9h0000gn/T/ipatool20220117-39826-jo4ts7/thinned-out/arm64/Payload/CanalSurTV.app/Frameworks/JWPlayerKit.framework/JWPlayerKit.dSYM --strip-swift-symbols /var/folders/9r/ggfdl08s5ds_k271dkw3ff9h0000gn/T/ipatool20220117-39826-jo4ts7/thinned-in/arm64/Payload/CanalSurTV.app/Frameworks/JWPlayerKit.framework/JWPlayerKit
Status: pid 40852 exit 1_

My file IDEDistributionPipeline.log show this issue:

...
'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/lib/darwin/libclang_rt.ios.a', '-o', '/private/var/folders/9r/ggfdl08s5ds_k271dkw3ff9h0000gn/T/JWPlayerKith1a2r4_k/JWPlayerKit.arm64.out']
    -= Output =-
    ld: warning: -sdk_version and -platform_version are not compatible, ignoring -sdk_version
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_GCKCastContext", referenced from:
          objc-class-ref in 099.o
          objc-class-ref in 134.o
          objc-class-ref in 203.o
      "_OBJC_CLASS_$_GCKImage", referenced from:
          objc-class-ref in 134.o
      "_OBJC_CLASS_$_GCKMediaInformationBuilder", referenced from:
          objc-class-ref in 134.o
      "_OBJC_CLASS_$_GCKMediaLoadOptions", referenced from:
          objc-class-ref in 134.o
      "_OBJC_CLASS_$_GCKMediaMetadata", referenced from:
          objc-class-ref in 134.o
      "_OBJC_CLASS_$_GCKMediaSeekOptions", referenced from:
          objc-class-ref in 134.o
      "_OBJC_CLASS_$_GCKMediaTrack", referenced from:
          objc-class-ref in 118.o
          objc-class-ref in 134.o
          objc-class-ref in 152.o
      "_OBJC_CLASS_$_GCKRequest", referenced from:
          objc-class-ref in 099.o
      "_OBJC_CLASS_$_IMAAVPlayerVideoDisplay", referenced from:
          objc-class-ref in 120.o
      "_OBJC_CLASS_$_IMAAdDisplayContainer", referenced from:
          objc-class-ref in 120.o
          objc-class-ref in 154.o
      "_OBJC_CLASS_$_IMAAdsLoader", referenced from:
          objc-class-ref in 120.o
          objc-class-ref in 143.o
          objc-class-ref in 154.o
      "_OBJC_CLASS_$_IMAAdsRenderingSettings", referenced from:
          objc-class-ref in 120.o
          objc-class-ref in 143.o
          objc-class-ref in 154.o
      "_OBJC_CLASS_$_IMAAdsRequest", referenced from:
          objc-class-ref in 154.o
      "_OBJC_CLASS_$_IMACuepoint", referenced from:
          objc-class-ref in 118.o
          objc-class-ref in 152.o
      "_OBJC_CLASS_$_IMAFriendlyObstruction", referenced from:
          objc-class-ref in 082.o
      "_OBJC_CLASS_$_IMALiveStreamRequest", referenced from:
          objc-class-ref in 120.o
      "_OBJC_CLASS_$_IMAPictureInPictureProxy", referenced from:
          objc-class-ref in 154.o
      "_OBJC_CLASS_$_IMASettings", referenced from:
          objc-class-ref in 120.o
          objc-class-ref in 143.o
          objc-class-ref in 154.o
      "_OBJC_CLASS_$_IMAVODStreamRequest", referenced from:
          objc-class-ref in 120.o
      "_kGCKMetadataKeyTitle", referenced from:
          __hidden#19800_ in 134.o
    ld: symbol(s) not found for architecture arm64
    Exited with 1

### Environment

- Mac mini (m1,2020)
- macOs Monterrey version 12.1
- JW Player SDK version 4.3.1_3

**Comment by david-almaguer** [comment]
Hey @jmltoro, thanks for contacting us.

In order to have a clear context of your issue, could you tell me if you are using the GoogleCast SDK and/or the GoogleIMA SDK in your app?

**Comment by david-almaguer** [comment]
@jmltoro We are currently working on a fix, stay tuned for the next release.

**Comment by david-almaguer** [comment]
@jmltoro This issue is fixed now, please update JWPlayerKit to new release version 4.4.1
