### ISSUE TITLE
Hide jwplayer buttons

### ISSUE THREAD

**Issue by PushkaryadavBrainvire** [jwplayer/jwplayer-ios-bestPracticeApps#89]
How to hide JWPlayer buttons as more button and pip button in default JWPlayerViewController

**Comment by ishteyaque06** [comment]
After configuring JWPLayer use 
 self.playerController.setVisibility(.hidden, for: [.languagesButton, .pictureInPictureButton, .airplayButton,.chromecastButton, .settingsButton,.nextButton,.previousButton])
